# Generated by Django 4.1.7 on 2023-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_options_alter_category_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'Customer', 'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
